name: Deploy Telegram Bot

on:
  push:
    branches:
      - main  # срабатывать при пуше в ветку main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонируем репозиторий
      - name: Check out code
        uses: actions/checkout@v3

      # 2. Устанавливаем Python (если захотим локальные тесты)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # 3. Устанавливаем зависимости (для тестов, линтеров, и т.д.)
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      # 4. (Опционально) Запускаем тесты
      - name: Run tests
        run: |
          echo "No tests yet"
          # Пример, если есть тесты:
          # pytest

      - name: Test SSH connection
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: echo "SSH connection successful!"
          
      - name: Add server to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/telegram-bot-photo/bot
            git pull origin main
            docker build -t telegram-bot-photo .
            docker stop bot-container || true
            docker rm bot-container || true
            docker run -d --name bot-container -p 8080:8080 telegram-bot-photo
        
